server:
  port: 8050

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka/

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      httpclient:
        connect-timeout: 5000
        response-timeout: 10000

      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_UNIQUE

      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: '*'
            allowedMethods: "*"
            allowedHeaders: "*"
      routes:
        - id: m1_tariffs_router
          uri: lb://MS1TARIFFS
          predicates:
            - Path=/api/tariffs/**
        - id: m2_dscqty_router
          uri: lb://MS2DSCQTY
          predicates:
            - Path=/api/dscqty/**
        - id: m3_dscfreq_router
          uri: lb://MS3DSCFREQ
          predicates:
            - Path=/api/dscfreq/**
        - id: m4_tariffsspecialday_router
          uri: lb://MS4TARIFFSSPECIALDAY
          predicates:
            - Path=/api/specialday/**
        - id: m5_bookingsandreceipt_router
          uri: lb://MS5BOOKINGSANDRECEIPT
          predicates:
            - Path=/api/bookings/**, /api/receipts/**
        - id: m6_rack_router
          uri: lb://MS6RACK
          predicates:
            - Path=/api/rack/**
        - id: m7_reports_router
          uri: lb://MS7REPORTS
          predicates:
            - Path=/api/reports/**
